### ISSUE TITLE
Establish SVG Elements

### ISSUE THREAD

**Issue by curran** [unhcr/dataviz-streamgraph-explorer#12]
The red areas here need to be added as SVG elements:
![sketch ui design protypes - svg areas](https://user-images.githubusercontent.com/3186357/29659435-28d0a46c-88b6-11e7-98de-8ab801a46995.png)

These SVG elements should change in size to respect the Semantic UI grid layout. I'm not sure exactly what kind of resize behavior we want. Perhaps for Desktop the SVG elements should reach exactly to the bottom of the display, and for mobile they should be a fixed aspect ratio and fill in the available width.

**Comment by matthewsmawfield** [comment]
I would agree with your suggestion, for desktop 100% height to the bottom
of the page with dynamic width resizing, with no fixed aspect ratio, while
on mobile using 100% width and a fixed aspect ratio to determine height
(while also probably having limited interactivity compared to the desktop
version).
