### ISSUE TITLE
Detect mobile

### ISSUE THREAD

**Issue by matthewsmawfield** [unhcr/dataviz-streamgraph-explorer#13]
How do you best want to handle the mobile vs desktop logic in the code? In previous projects, I have used a function to detect mobile and then set a variable isMobile, which can be used as a conditional in other parts of the code, such as SVG resizing. Do you have another approach you would recommend?

**Comment by curran** [comment]
I researched this a few days ago and found this to look like a nice simple solution:

```js
function detectmob() {
   if(window.innerWidth <= 800 && window.innerHeight <= 600) {
     return true;
   } else {
     return false;
   }
}
```

From https://stackoverflow.com/questions/11381673/detecting-a-mobile-browser

**Comment by matthewsmawfield** [comment]
Looks good to me.
