### ISSUE TITLE
click to escape drill-down slow

### ISSUE THREAD

**Issue by matthewsmawfield** [unhcr/dataviz-streamgraph-explorer#60]
when you click on a stream to drill-down, and then click to go back, it is a bit slow. could it be improved by keeping the default state in memory and avoiding re-calculations?

**Comment by curran** [comment]
I've noticed this as well. We can try doing more to optimize performance. Some ideas:

 * We are "simulating" the API using a Web Worker, but the overhead of this may be causing performance issues.
 * We could [memoize](https://en.wikipedia.org/wiki/Memoization) or cache the query results for a given set of API query parameters, so we don't need to filter each time.
 * We can tweak the parameters for the max number of streams to show.
