### ISSUE TITLE
Responsive Layout

### ISSUE THREAD

**Issue by curran** [unhcr/dataviz-streamgraph-explorer#7]
![gimp_boxes](https://user-images.githubusercontent.com/68416/29622233-8115c902-8840-11e7-9743-1507a412d2cf.png)

As one of the first things, let's set up a layout of nested boxes that changes depending on whether we're on a mobile device or not, and also responds to resize.

**Comment by curran** [comment]
From an internal discussion:

> could we also agree/decide on what should be svg content and what html

My thought on this point is that I think it would be quite clean if we use a single SVG element for everything, and use `preserveAspectRatio="xMinYMin slice"` to have the SVG fill the space. We can write code that will re-layout the arrangement and resize the SVG at a certain width breakpoint. I believe this would be straightforward to do.

We could also evaluate other options like Flexbox, Bootstrap Grid, or Semantic UI Grid, but my gut feeling is that using those will introduce more complexity.

**Comment by curran** [comment]
Although, the one thing that strikes me as a potentially great fit for HTML is the `typeSelector` widget on the top. But that too seems relatively straightforward to produce with SVG as well.

Maybe as a first pass we can try everything as SVG, and see what we might want to swap out later?

**Comment by matthewsmawfield** [comment]
this is how I would probably tackle it, using 2 svgs and leveraging bootstrap/semantic UI grid to effortlessly make the type selectors and the left/right panel responsive

![sketch ui design protypes - svg areas](https://user-images.githubusercontent.com/3186357/29659435-28d0a46c-88b6-11e7-98de-8ab801a46995.png)

**Comment by matthewsmawfield** [comment]
with this approach i guess the dropdown series selector, would also be html

**Comment by matthewsmawfield** [comment]
i dont think either approach is wrong. some visualisaions i have worked on such as popstats uses one single svg, whereas others, such as the historic population change over time, uses multiple svg objects interspersed with html. i would say both approaches are valid and have distinct advantages and disadvantages

**Comment by curran** [comment]
That division makes total sense. It would be a good way to start integrating the work from https://github.com/unhcr/dataviz-styleguide as well, and see how it plays out.

Here's a rough estimation of which Semantic UI components we could use:

 * https://semantic-ui.com/collections/grid.html for responsive layout and boxes structure. This works almost exactly the same as Bootstrap. The main difference I can see is that there are a total of 16 "units" of width, where in Bootstrap there are 12.
 * https://semantic-ui.com/modules/checkbox.html For the type selector. Their design is so similar, we just need to tweak a few Less variables for color and sizing:

![image](https://user-images.githubusercontent.com/68416/29659950-756448c0-88dd-11e7-8208-b83f7a0e97c5.png)

 * https://semantic-ui.com/elements/button.html for "reset selection"

![image](https://user-images.githubusercontent.com/68416/29659979-92a205a8-88dd-11e7-979f-bf0969daf0d0.png)

 * https://semantic-ui.com/views/statistic.html For the numbers on the top right

![image](https://user-images.githubusercontent.com/68416/29660007-b27e45da-88dd-11e7-8362-015d20129d15.png)

**Comment by matthewsmawfield** [comment]
ok perfect!
