### ISSUE TITLE
Update Document Structure

### ISSUE THREAD

**Issue by curran** [unhcr/dataviz-streamgraph-explorer#77]
Here's a first pass from Trello by @vidonne 
![image](https://user-images.githubusercontent.com/68416/31181364-beb3954a-a93e-11e7-8a00-d82c0641dc04.png)

**Comment by vidonne** [comment]
Added slider to component
<img width="1960" alt="data_viz_guideline___trello" src="https://user-images.githubusercontent.com/1830612/31181629-1842193c-a922-11e7-8316-668ad4b6417c.png">

**Comment by curran** [comment]
Oops wrong repo! Moved over to https://github.com/unhcr/dataviz-styleguide/issues/84
