### ISSUE TITLE
Smaller font for smaller screens

### ISSUE THREAD

**Issue by curran** [unhcr/dataviz-streamgraph-explorer#89]
![image](https://user-images.githubusercontent.com/68416/31655241-e950bda8-b345-11e7-9cc3-3d9145143742.png)

![image](https://user-images.githubusercontent.com/68416/31655274-fef4591c-b345-11e7-9889-b0b2a1c7a9ab.png)

**Comment by curran** [comment]
@matthewsmawfield @vidonne Which font size should change here when it gets smaller? Definitely the tick marks in the middle, not sure what else if anything should get smaller.

**Comment by matthewsmawfield** [comment]
we should reduce the text size on the bars in right column. and possibly
the radio option labels
