### ISSUE TITLE
Design Data Flow

### ISSUE THREAD

**Issue by curran** [unhcr/dataviz-streamgraph-explorer#9]
I propose we work with [reactive-model](https://github.com/datavis-tech/reactive-model) so we can code in terms of data flow, and not need to worry about the logistics of when different parts of our code execute.

Given that we'll use the packed 2MB data for now, and we'll use an API later, we need to design the data flow graph such that we can cleanly swap out the data source, and everything will still function correctly.

This is approximately how it might look:
![image](https://user-images.githubusercontent.com/68416/29665728-125d4c20-88f3-11e7-99fe-7092eb2cbda4.png)

Then we can write the visualization code to solely depend on `srcDataAggregated` and `destDataAggregated`, and make sure they get the same values no matter which data backend is used.

**Comment by matthewsmawfield** [comment]
This looks great to me.

**Comment by curran** [comment]
Revised sketch of data flow:

![image](https://user-images.githubusercontent.com/68416/29809917-940f3c3a-8cbb-11e7-898a-0e357c9d81ad.png)

**Comment by curran** [comment]
Closing, as this is pretty much settled.
